### ISSUE TITLE
Cannot find module commander

### ISSUE THREAD

**Issue by dolftax** [ekoeryanto/vuepress-plugin-sitemap#13]
```
[9/01/19 4:07:01] ➜  web git:(master) sudo npm install -g vuepress-plugin-sitemap
/usr/local/bin/vuepress-sitemap -> /usr/local/lib/node_modules/vuepress-plugin-sitemap/cli.js
npm WARN vuepress-plugin-sitemap@2.1.1 requires a peer of chalk@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vuepress-plugin-sitemap@2.1.1 requires a peer of commander@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vuepress-plugin-sitemap@2.1.1 requires a peer of esm@^3.0.0 but none is installed. You must install peer dependencies yourself.

+ vuepress-plugin-sitemap@2.1.1
added 5 packages from 6 contributors in 3.614s
[9/01/19 4:07:24] ➜  web git:(master) vuepress-sitemap
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vuepress-plugin-sitemap/cli.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Comment by dolftax** [comment]
Installed peer deps `chalk`, `esm` and `commander`.
